//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.21 at 06:37:09 PM IST 
//


package IndividualSymbolDescription;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the IndividualSymbolDescription package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WIPOClassificationsClassificationHeadingDescriptionEmdash_QNAME = new QName("", "emdash");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: IndividualSymbolDescription
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WIPOSymbolDescription.Classification }
     * 
     */
    public WIPOSymbolDescription.Classification createWIPOClassificationsClassification() {
        return new WIPOSymbolDescription.Classification();
    }

    /**
     * Create an instance of {@link WIPOSymbolDescription.Classification.Heading }
     * 
     */
    public WIPOSymbolDescription.Classification.Heading createWIPOClassificationsClassificationHeading() {
        return new WIPOSymbolDescription.Classification.Heading();
    }

    /**
     * Create an instance of {@link WIPOSymbolDescription }
     * 
     */
    public WIPOSymbolDescription createWIPOClassifications() {
        return new WIPOSymbolDescription();
    }

    /**
     * Create an instance of {@link WIPOSymbolDescription.Classification.Heading.Description }
     * 
     */
    public WIPOSymbolDescription.Classification.Heading.Description createWIPOClassificationsClassificationHeadingDescription() {
        return new WIPOSymbolDescription.Classification.Heading.Description();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "emdash", scope = WIPOSymbolDescription.Classification.Heading.Description.class)
    public JAXBElement<String> createWIPOClassificationsClassificationHeadingDescriptionEmdash(String value) {
        return new JAXBElement<String>(_WIPOClassificationsClassificationHeadingDescriptionEmdash_QNAME, String.class, WIPOSymbolDescription.Classification.Heading.Description.class, value);
    }

}
