//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.21 at 06:37:58 PM IST 
//


package AllipcClassificationSymbol;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the AllipcClassificationSymbol package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WIPOClassificationsClassifications_QNAME = new QName("", "classifications");
    private final static QName _WIPOClassificationsClassificationsClassification_QNAME = new QName("", "classification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: AllipcClassificationSymbol
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WIPOSymbolDescription }
     * 
     */
    public WIPOSymbolsOfVersion createWIPOClassifications() {
        return new WIPOSymbolsOfVersion();
    }

    /**
     * Create an instance of {@link WIPOSymbolDescription.Classifications.Classification }
     * 
     */
    public WIPOSymbolsOfVersion.Classifications.Classification createWIPOClassificationsClassificationsClassification() {
        return new WIPOSymbolsOfVersion.Classifications.Classification();
    }

    /**
     * Create an instance of {@link WIPOSymbolDescription.Classifications }
     * 
     */
    public WIPOSymbolsOfVersion.Classifications createWIPOClassificationsClassifications() {
        return new WIPOSymbolsOfVersion.Classifications();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WIPOSymbolDescription.Classifications }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "classifications", scope = WIPOSymbolsOfVersion.class)
    public JAXBElement<WIPOSymbolsOfVersion.Classifications> createWIPOClassificationsClassifications(WIPOSymbolsOfVersion.Classifications value) {
        return new JAXBElement<WIPOSymbolsOfVersion.Classifications>(_WIPOClassificationsClassifications_QNAME, WIPOSymbolsOfVersion.Classifications.class, WIPOSymbolsOfVersion.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WIPOSymbolDescription.Classifications.Classification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "classification", scope = WIPOSymbolsOfVersion.Classifications.class)
    public JAXBElement<WIPOSymbolsOfVersion.Classifications.Classification> createWIPOClassificationsClassificationsClassification(WIPOSymbolsOfVersion.Classifications.Classification value) {
        return new JAXBElement<WIPOSymbolsOfVersion.Classifications.Classification>(_WIPOClassificationsClassificationsClassification_QNAME, WIPOSymbolsOfVersion.Classifications.Classification.class, WIPOSymbolsOfVersion.Classifications.class, value);
    }

}
