//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 11:47:59 PM IST 
//




import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TABLE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ROW" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ROW_VERSION" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="IPC_EDITION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IPC_SECTION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IPC_CLASS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IPC_SUBCLASS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IPC_GROUP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IPC_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IPC_SUBGROUP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="EXPORT_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LANGUAGE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NOTES" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "table"
})
@XmlRootElement(name = "EXPORT")
public class EXPORT {

    @XmlElement(name = "TABLE", required = true)
    protected EXPORT.TABLE table;
    @XmlAttribute(name = "EXPORT_ID")
    protected String exportid;
    @XmlAttribute(name = "LANGUAGE")
    protected String language;
    @XmlAttribute(name = "NOTES")
    protected String notes;
    @XmlAttribute(name = "VERSION")
    protected String version;

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link EXPORT.TABLE }
     *     
     */
    public EXPORT.TABLE getTABLE() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXPORT.TABLE }
     *     
     */
    public void setTABLE(EXPORT.TABLE value) {
        this.table = value;
    }

    /**
     * Gets the value of the exportid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPORTID() {
        return exportid;
    }

    /**
     * Sets the value of the exportid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPORTID(String value) {
        this.exportid = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUAGE() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUAGE(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTES() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTES(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ROW" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ROW_VERSION" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="IPC_EDITION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IPC_SECTION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IPC_CLASS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IPC_SUBCLASS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IPC_GROUP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IPC_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IPC_SUBGROUP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class TABLE {

        @XmlElement(name = "ROW")
        protected List<EXPORT.TABLE.ROW> row;
        @XmlAttribute(name = "NAME")
        protected String name;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getROW().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EXPORT.TABLE.ROW }
         * 
         * 
         */
        public List<EXPORT.TABLE.ROW> getROW() {
            if (row == null) {
                row = new ArrayList<EXPORT.TABLE.ROW>();
            }
            return this.row;
        }
        
        public void addROW(EXPORT.TABLE.ROW updatedRow) {
            if (row == null) {
                row = new ArrayList<EXPORT.TABLE.ROW>();
            }
           row.add(updatedRow);
        }
        
        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNAME() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNAME(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ROW_VERSION" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="IPC_EDITION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IPC_SECTION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IPC_CLASS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IPC_SUBCLASS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IPC_GROUP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IPC_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IPC_SUBGROUP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rowversion",
            "ipceditioncode",
            "ipcsectioncode",
            "ipcclasscode",
            "ipcsubclasscode",
            "ipcgroupcode",
            "ipcname",
            "ipcsubgroupcode"
        })
        public static class ROW {

            @XmlElement(name = "ROW_VERSION")
            protected byte rowversion;
            @XmlElement(name = "IPC_EDITION_CODE", required = true)
            protected String ipceditioncode;
            @XmlElement(name = "IPC_SECTION_CODE", required = true)
            protected String ipcsectioncode;
            @XmlElement(name = "IPC_CLASS_CODE", required = true)
            protected String ipcclasscode;
            @XmlElement(name = "IPC_SUBCLASS_CODE", required = true)
            protected String ipcsubclasscode;
            @XmlElement(name = "IPC_GROUP_CODE", required = true)
            protected String ipcgroupcode;
            @XmlElement(name = "IPC_NAME", required = true)
            protected String ipcname;
            @XmlElement(name = "IPC_SUBGROUP_CODE", required = true)
            protected String ipcsubgroupcode;

            /**
             * Gets the value of the rowversion property.
             * 
             */
            public byte getROWVERSION() {
                return rowversion;
            }

            /**
             * Sets the value of the rowversion property.
             * 
             */
            public void setROWVERSION(byte value) {
                this.rowversion = value;
            }

            /**
             * Gets the value of the ipceditioncode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIPCEDITIONCODE() {
                return ipceditioncode;
            }

            /**
             * Sets the value of the ipceditioncode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIPCEDITIONCODE(String value) {
                this.ipceditioncode = value;
            }

            /**
             * Gets the value of the ipcsectioncode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIPCSECTIONCODE() {
                return ipcsectioncode;
            }

            /**
             * Sets the value of the ipcsectioncode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIPCSECTIONCODE(String value) {
                this.ipcsectioncode = value;
            }

            /**
             * Gets the value of the ipcclasscode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIPCCLASSCODE() {
                return ipcclasscode;
            }

            /**
             * Sets the value of the ipcclasscode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIPCCLASSCODE(String value) {
                this.ipcclasscode = value;
            }

            /**
             * Gets the value of the ipcsubclasscode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIPCSUBCLASSCODE() {
                return ipcsubclasscode;
            }

            /**
             * Sets the value of the ipcsubclasscode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIPCSUBCLASSCODE(String value) {
                this.ipcsubclasscode = value;
            }

            /**
             * Gets the value of the ipcgroupcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIPCGROUPCODE() {
                return ipcgroupcode;
            }

            /**
             * Sets the value of the ipcgroupcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIPCGROUPCODE(String value) {
                this.ipcgroupcode = value;
            }

            /**
             * Gets the value of the ipcname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIPCNAME() {
                return ipcname;
            }

            /**
             * Sets the value of the ipcname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIPCNAME(String value) {
                this.ipcname = value;
            }

            /**
             * Gets the value of the ipcsubgroupcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIPCSUBGROUPCODE() {
                return ipcsubgroupcode;
            }

            /**
             * Sets the value of the ipcsubgroupcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIPCSUBGROUPCODE(String value) {
                this.ipcsubgroupcode = value;
            }

        }

    }

}
